M48
; DRILL file {KiCad 7.0.9} date Wed Jan 10 08:50:18 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-10T08:50:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X-0.5719Y-0.9094
T2
X-0.2244Y0.9252
X-0.2244Y-0.9252
X0.2244Y0.9252
X0.2244Y-0.9252
T0
M30
